@MyBackend_HostAddress = http://localhost:5294


### initial landing root page
GET {{MyBackend_HostAddress}}/
Accept: text/plain


### Get all tasks
GET {{MyBackend_HostAddress}}/tasks
Accept: application/json

### Add a new task
POST {{MyBackend_HostAddress}}/tasks
Content-Type: application/json

{
  "title": "Sample Task",
  "isCompleted": false
}

### Update a task
# Replace {id} with the actual task id you want to update, for example: 1
PUT {{MyBackend_HostAddress}}/tasks/1
Content-Type: application/json

{
  "title": "Updated Task Title",
  "isCompleted": true
}

### Delete a task
# Replace {id} with the actual task id you want to delete, for example: 1
DELETE {{MyBackend_HostAddress}}/tasks/1

###